"""Report Generator for SWARMICA v13.0 - Autonomous Physical Law Discovery"""

import json
import math
from datetime import datetime
from typing import List, Dict, Any
from dataclasses import dataclass, asdict


@dataclass
class DiscoveryReport:
    """Data class for Physics Discovery results"""
    timestamp: str
    config: Dict[str, Any]
    discovered_pde: str
    coefficients: Dict[str, float]
    verification: Dict[str, Any]
    summary: Dict[str, Any]


class DiscoveryReportGenerator:
    """Generate comprehensive reports from Physics Discovery"""
    
    def __init__(self, reports_dir: str = "reports"):
        self.reports_dir = reports_dir
    
    def generate_from_engine(self, engine, discovery_result: Dict) -> DiscoveryReport:
        """Generate report from DiscoveryEngine instance"""
        config = {
            'N': engine.N,
            'dt': engine.dt,
            'alpha': engine.alpha
        }
        
        verification = discovery_result.get('verification', {})
        coefficients = discovery_result.get('coefficients', {})
        
        summary = {
            'num_terms': discovery_result.get('num_terms', 0),
            'sparsity': discovery_result.get('sparsity', 0),
            'has_diffusion': verification.get('has_diffusion', False),
            'has_advection': verification.get('has_advection', False),
            'has_reaction': verification.get('has_reaction', False),
            'verified': verification.get('verified', False)
        }
        
        return DiscoveryReport(
            timestamp=datetime.now().isoformat(),
            config=config,
            discovered_pde=discovery_result.get('discovered_pde', 'No PDE discovered'),
            coefficients=coefficients,
            verification=verification,
            summary=summary
        )
    
    def save_json(self, report: DiscoveryReport, filename: str = None) -> str:
        if filename is None:
            filename = f"discovery_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        
        filepath = f"{self.reports_dir}/{filename}"
        with open(filepath, 'w') as f:
            json.dump(asdict(report), f, indent=2)
        print(f"✅ JSON saved: {filepath}")
        return filepath
    
    def save_markdown(self, report: DiscoveryReport, filename: str = None) -> str:
        if filename is None:
            filename = f"discovery_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        
        lines = []
        lines.append(f"# SWARMICA v13.0 Physical Law Discovery Report")
        lines.append(f"*Generated: {report.timestamp}*")
        lines.append("")
        lines.append("## Configuration")
        for k, v in report.config.items():
            lines.append(f"- **{k}**: {v}")
        lines.append("")
        lines.append("## Discovered PDE")
        lines.append("```")
        lines.append(report.discovered_pde)
        lines.append("```")
        lines.append("")
        lines.append("## Coefficients")
        for term, coeff in report.coefficients.items():
            lines.append(f"- **{term}**: {coeff:.4f}")
        lines.append("")
        lines.append("## Verification")
        lines.append(f"- **Verified**: {report.verification.get('verified', False)}")
        lines.append(f"- **Diffusion Term**: {'✓' if report.summary['has_diffusion'] else '✗'}")
        lines.append(f"- **Advection Term**: {'✓' if report.summary['has_advection'] else '✗'}")
        lines.append(f"- **Reaction Term**: {'✓' if report.summary['has_reaction'] else '✗'}")
        if report.verification.get('warnings'):
            lines.append(f"- **Warnings**: {', '.join(report.verification['warnings'])}")
        lines.append("")
        lines.append("## Summary")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Number of Terms | {report.summary['num_terms']} |")
        lines.append(f"| Sparsity | {report.summary['sparsity']:.2%} |")
        lines.append(f"| Physically Valid | {report.summary['verified']} |")
        lines.append("")
        lines.append("## PDE Discovery Formulation")
        lines.append("```")
        lines.append("∂u/∂t = Θ(u)·ξ")
        lines.append("min ||y - Θξ||² + α||ξ||₁")
        lines.append("```")
        lines.append("")
        lines.append("---")
        lines.append("*Report generated by SWARMICA v13.0 Physics Discovery Engine*")
        
        filepath = f"{self.reports_dir}/{filename}"
        with open(filepath, 'w') as f:
            f.write("\n".join(lines))
        print(f"✅ Markdown saved: {filepath}")
        return filepath
    
    def save_csv(self, report: DiscoveryReport, filename: str = None) -> str:
        if filename is None:
            filename = f"discovery_metrics_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        
        filepath = f"{self.reports_dir}/{filename}"
        with open(filepath, 'w') as f:
            f.write("term,coefficient\n")
            for term, coeff in report.coefficients.items():
                f.write(f"{term},{coeff:.6f}\n")
        print(f"✅ CSV saved: {filepath}")
        return filepath
    
    def print_summary(self, report: DiscoveryReport):
        print("\n" + "=" * 60)
        print("🔬 SWARMICA v13.0 Physics Discovery Summary")
        print("=" * 60)
        print(f"Discovered PDE: {report.discovered_pde[:80]}...")
        print(f"Number of terms: {report.summary['num_terms']}")
        print(f"Sparsity: {report.summary['sparsity']:.2%}")
        print(f"Physically Valid: {report.summary['verified']}")
        print("=" * 60)


def create_discovery_report_generator() -> DiscoveryReportGenerator:
    return DiscoveryReportGenerator()
